<?xml version="1.0" encoding="UTF-8"?>
<!--
    Nombre: Miguel Tejero Garcia-Abad
    Curso: DAW1
    Fecha: 4/04/2025
    Ejercicio: 3
    -->
<!--Correción de errores-->

<!DOCTYPE aeropuertos[
    <!ELEMENT aeropuertos(aeropuerto*)>
    <!ELEMENT aeropuerto(nombre, cerrado)>
    <!ELEMENT nombre(#PCDATA)>
    <!ELEMENT cerrado(#PCDATA)>
]>

<aeropuertos>
    <aeropuerto>
        <nombre>Berlín Schönefeld (SFX)</nombre>
        <cerrado/>
    </aeropuertos>
    <aeropuerto>
        <nombre>Berlín Tempelhof (THF)</nombre>
        <cerrado/>
    </aeropuerto>
</aeropuertos>