<?xml version="1.0" encoding="UTF-8"?>
<!--
    Nombre: Miguel Tejero Garcia-Abad
    Curso: DAW1
    Fecha: 4/04/2025
    Ejercicio: 4
    -->
<!--Correción de errores-->

<!DOCTYPE vuelos[
    <!ELEMENT vuelos(vuelo*)>
    <!ELEMENT vuelo(origen, destino)>
    <!ELEMENT origen(#PCDATA)>
    <!ELEMENT destino(#PCDATA)>
]>

<vuelos>
    <vuelo>
        <origen>Valencia (VLC) </origen>
        <destino>Londres Heathrow (LHR) </destino>
    </vuelo>
    <vuelo>
        <origen>París Charles de Gaulle (CDG)</origen>
        <destino>Berlín Schönefeld (SFX)</destino>
    </vuelo>
</vuelos>