<?xml version="1.0" encoding="UTF-8"?>
<!--
    Nombre: Miguel Tejero Garcia-Abad
    Curso: DAW1
    Fecha: 4/04/2025
    Ejercicio: 6
    -->
<!--CorreciÃ³n de error-->
<!DOCTYPE escritores[
    <!ELEMENT escritores(escritor*)>
    <!ELEMENT escritor(nombre, nacimiento)>
    <!ELEMENT nombre(#PCDATA)>
    <!ELEMENT nacimiento(#PCDATA)>
]>

<escritores>
    <escritor>
        <nombre>Mario Vargas Llosa</nombre>
        <nacimiento>28 de marzo de 1936</nacimiento>
    </escritor>
    <escritor>
        <nombre>Milan Kundera</nombre>
        <nacimiento>1 de abril de 1929</nacimiento>
    </escritor>
</escritores>