<?xml version="1.0" encoding="UTF-8"?>
<!--
    Nombre: Miguel Tejero Garcia-Abad
    Curso: DAW1
    Fecha: 2/04/2025
    Ejercicio: 3
    -->
<!--Panel de aeropuerto-->
<!DOCTYPE panel [
    <!ELEMENT panel (nombreAeropuerto, fecha, vuelos)>
    <!ELEMENT nombreAeropuerto (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT vuelos (vuelo+)>

    <!ELEMENT vuelo (origen, destino, horaSalida, horaLlegada, compania, diario?)>
    <!ATTLIST vuelo codigo ID #REQUIRED>
    <!ATTLIST vuelo estado (C | E | R) "E">

    <!ELEMENT origen (#PCDATA)>
    <!ELEMENT destino (#PCDATA)>
    <!ELEMENT horaSalida (#PCDATA)>
    <!ELEMENT horaLlegada (#PCDATA)>
    <!ELEMENT compania (#PCDATA)>
    <!ELEMENT diario EMPTY>
]>
<panel>
    <nombreAeropuerto>Barajas</nombreAeropuerto>
    <fecha>2025-04-02</fecha>
    
    <vuelos>
        <vuelo codigo="1234" estado="E">
            <origen>Madrid</origen>
            <destino>Barcelona</destino>
            <horaSalida>10:30</horaSalida>
            <horaLlegada>11:45</horaLlegada>
            <compania>Raynair</compania>
            <diario/>
        </vuelo>

        <vuelo codigo="4321" estado="R">
            <origen>París</origen>
            <destino>Madrid</destino>
            <horaSalida>12:00</horaSalida>
            <horaLlegada>14:15</horaLlegada>
            <compania>Air France</compania>
        </vuelo>

        <vuelo codigo="5678" estado="C">
            <origen>Berlín</origen>
            <destino>Madrid</destino>
            <horaSalida>15:00</horaSalida>
            <horaLlegada>17:20</horaLlegada>
            <compania>Iberia</compania>
            <diario/>
        </vuelo>
    </vuelos>
</panel>
